In [1]:
import pandas as pd
import glob

# Where raw txt files were stored
RAW_PATH = "/Users/rosellazheng/Desktop/US_VitalStatistics/"
pattern = RAW_PATH + "Underlying Cause of Death, 20*.txt"

files = glob.glob(pattern)
print("Found files:", files)  # All are in there

# Combine all years
df = pd.concat((pd.read_csv(f, sep="\t") for f in files), ignore_index=True)

# Quick clean of column names
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

# 3. Save into project repo so everyone else can load this CSV
OUTPUT = "/Users/rosellazheng/Desktop/idsproject/vital_stats_2003_2015.csv"
df.to_csv(OUTPUT, index=False)

print("Saved clean CSV to:", OUTPUT)

Found files: ['/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2009.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2008.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2003.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2014.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2015.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2005.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2011.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2010.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2004.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2012.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2006.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2007.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2013.txt']
Saved clean CSV to: /Users/rosellazheng/Desktop/idsproject/vital_stats_2003_2015.csv

In [ ]:
print("Total rows after concat:", len(df))  # 57436

Total rows after concat: 57436

In [3]:
# load the data
df = pd.read_csv(OUTPUT)

# basic info
print(f"Raw data shape: {df.shape}")

# quick look at the raw data
df

Raw data shape: (57436, 8)

,notes,county,county_code,year,year_code,drug/alcohol_induced_cause,drug/alcohol_induced_cause_code,deaths
0,NaN,"Autauga County, AL",1001.0,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,408.0
1,NaN,"Baldwin County, AL",1003.0,2009.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,29.0
2,NaN,"Baldwin County, AL",1003.0,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,1669.0
3,NaN,"Barbour County, AL",1005.0,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,299.0
4,NaN,"Bibb County, AL",1007.0,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,207.0
...,...,...,...,...,...,...,...,...
57431,Suggested Citation: Centers for Disease Contro...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57432,"1999-2017 on CDC WONDER Online Database, relea...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
57433,compiled from data provided by the 57 vital st...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57434,at http://wonder.cdc.gov/ucd-icd10.html on Oct...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57435,---,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.columns.unique()  # found all the column names

Index(['notes', 'county', 'county_code', 'year', 'year_code',
       'drug/alcohol_induced_cause', 'drug/alcohol_induced_cause_code',
       'deaths'],
      dtype='object')

In [5]:
df_clean = df[df["notes"].isna()]  # this is droping all the weird notes

In [ ]:
print("Total rows after concat:", len(df_clean))  # 57241

Total rows after concat: 57241

In [7]:
df_clean = df_clean.drop(columns=["notes", "year_code"])

In [8]:
print(df_clean.columns)

Index(['county', 'county_code', 'year', 'drug/alcohol_induced_cause',
       'drug/alcohol_induced_cause_code', 'deaths'],
      dtype='object')

In [9]:
df_clean.head()

,county,county_code,year,drug/alcohol_induced_cause,drug/alcohol_induced_cause_code,deaths
0,"Autauga County, AL",1001.0,2009.0,All other non-drug and non-alcohol causes,O9,408.0
1,"Baldwin County, AL",1003.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,29.0
2,"Baldwin County, AL",1003.0,2009.0,All other non-drug and non-alcohol causes,O9,1669.0
3,"Barbour County, AL",1005.0,2009.0,All other non-drug and non-alcohol causes,O9,299.0
4,"Bibb County, AL",1007.0,2009.0,All other non-drug and non-alcohol causes,O9,207.0

In [10]:
# here we want to split the county column and make a new one just for state
df_clean[["county", "state"]] = df_clean["county"].str.split(", ", expand=True)

In [11]:
df_clean  # here we see its in the format we want

,county,county_code,year,drug/alcohol_induced_cause,drug/alcohol_induced_cause_code,deaths,state
0,Autauga County,1001.0,2009.0,All other non-drug and non-alcohol causes,O9,408.0,AL
1,Baldwin County,1003.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,29.0,AL
2,Baldwin County,1003.0,2009.0,All other non-drug and non-alcohol causes,O9,1669.0,AL
3,Barbour County,1005.0,2009.0,All other non-drug and non-alcohol causes,O9,299.0,AL
4,Bibb County,1007.0,2009.0,All other non-drug and non-alcohol causes,O9,207.0,AL
...,...,...,...,...,...,...,...
57416,Sweetwater County,56037.0,2013.0,All other non-drug and non-alcohol causes,O9,238.0,WY
57417,Teton County,56039.0,2013.0,All other non-drug and non-alcohol causes,O9,83.0,WY
57418,Uinta County,56041.0,2013.0,All other non-drug and non-alcohol causes,O9,130.0,WY
57419,Washakie County,56043.0,2013.0,All other non-drug and non-alcohol causes,O9,72.0,WY
57420,Weston County,56045.0,2013.0,All other non-drug and non-alcohol causes,O9,66.0,WY

In [ ]:
print("Total rows after concat:", len(df_clean))  # 57241

Total rows after concat: 57241

In [13]:
# extract states only used in research comparison
states_to_keepFL = ["FL", "GA", "SC", "NC"]
states_to_keepWA = ["WA", "OR", "MT", "CO"]
states_to_keep = states_to_keepFL + states_to_keepWA  # merge the lists
df_clean = df_clean[df_clean["state"].isin(states_to_keep)]

In [ ]:
print("Total rows after concat:", len(df_clean))  # 11375

Total rows after concat: 11375

In [15]:
# here we can change both county_code and year into int
df_clean.dtypes

county                              object
county_code                        float64
year                               float64
drug/alcohol_induced_cause          object
drug/alcohol_induced_cause_code     object
deaths                              object
state                               object
dtype: object

In [16]:
df_clean.dtypes

county                              object
county_code                        float64
year                               float64
drug/alcohol_induced_cause          object
drug/alcohol_induced_cause_code     object
deaths                              object
state                               object
dtype: object

In [17]:
df_clean

,county,county_code,year,drug/alcohol_induced_cause,drug/alcohol_induced_cause_code,deaths,state
414,Adams County,8001.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,52.0,CO
415,Adams County,8001.0,2009.0,Drug poisonings (overdose) Suicide (X60-X64),D2,15.0,CO
416,Adams County,8001.0,2009.0,All other alcohol-induced causes,A9,55.0,CO
417,Adams County,8001.0,2009.0,All other non-drug and non-alcohol causes,O9,2215.0,CO
418,Alamosa County,8003.0,2009.0,All other non-drug and non-alcohol causes,O9,101.0,CO
...,...,...,...,...,...,...,...
57207,Whatcom County,53073.0,2013.0,All other non-drug and non-alcohol causes,O9,1535.0,WA
57208,Whitman County,53075.0,2013.0,All other non-drug and non-alcohol causes,O9,252.0,WA
57209,Yakima County,53077.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,14.0,WA
57210,Yakima County,53077.0,2013.0,All other alcohol-induced causes,A9,29.0,WA
57211,Yakima County,53077.0,2013.0,All other non-drug and non-alcohol causes,O9,1819.0,WA

In [18]:
# check for catorgories and make final dataset
df_clean["drug/alcohol_induced_cause"].unique()

array(['Drug poisonings (overdose) Unintentional (X40-X44)',
       'Drug poisonings (overdose) Suicide (X60-X64)',
       'All other alcohol-induced causes',
       'All other non-drug and non-alcohol causes',
       'Alcohol poisonings (overdose) (X45, X65, Y15)',
       'Drug poisonings (overdose) Undetermined (Y10-Y14)',
       'All other drug-induced causes'], dtype=object)

In [19]:
# categories to drop
drop_categories = [
    "All other alcohol-induced causes",
    "All other non-drug and non-alcohol causes",
    "Alcohol poisonings (overdose) (X45, X65, Y15)",
]

# keep everything EXCEPT the above
df_overdose = df_clean[~df_clean["drug/alcohol_induced_cause"].isin(drop_categories)]

In [20]:
df_overdose

,county,county_code,year,drug/alcohol_induced_cause,drug/alcohol_induced_cause_code,deaths,state
414,Adams County,8001.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,52.0,CO
415,Adams County,8001.0,2009.0,Drug poisonings (overdose) Suicide (X60-X64),D2,15.0,CO
419,Arapahoe County,8005.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,71.0,CO
420,Arapahoe County,8005.0,2009.0,Drug poisonings (overdose) Suicide (X60-X64),D2,19.0,CO
426,Boulder County,8013.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,28.0,CO
...,...,...,...,...,...,...,...
57193,Spokane County,53063.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,48.0,WA
57194,Spokane County,53063.0,2013.0,Drug poisonings (overdose) Suicide (X60-X64),D2,15.0,WA
57199,Thurston County,53067.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,25.0,WA
57205,Whatcom County,53073.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,13.0,WA
57209,Yakima County,53077.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,14.0,WA

In [ ]:
print("Total rows after concat:", len(df_overdose))  # 2379

Total rows after concat: 2379

In [22]:
df_overdose["deaths"] = pd.to_numeric(df_overdose["deaths"], errors="coerce").astype(
    "Int64"
)
df_overdose["county"] = df_overdose["county"].astype("string")
df_overdose["county_code"] = df_overdose["county_code"].astype("Int64")
df_overdose["drug/alcohol_induced_cause"] = df_overdose[
    "drug/alcohol_induced_cause"
].astype("string")
df_overdose["drug/alcohol_induced_cause_code"] = df_overdose[
    "drug/alcohol_induced_cause_code"
].astype("string")
df_overdose["year"] = df_overdose["year"].astype(int)
df_overdose["county_code"] = df_overdose["county_code"].astype(int)
df_overdose["state"] = df_overdose["state"].astype("string")

/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_99977/3363942364.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["deaths"] = pd.to_numeric(df_overdose["deaths"], errors="coerce").astype(
/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_99977/3363942364.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["county"] = df_overdose["county"].astype("string")
/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_99977/3363942364.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["county_code"] = df_overdose["county_code"].astype("Int64")
/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_99977/3363942364.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["drug/alcohol_induced_cause"] = df_overdose[
/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_99977/3363942364.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["drug/alcohol_induced_cause_code"] = df_overdose[
/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_99977/3363942364.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["year"] = df_overdose["year"].astype(int)
/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_99977/3363942364.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["county_code"] = df_overdose["county_code"].astype(int)
/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_99977/3363942364.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["state"] = df_overdose["state"].astype("string")

In [ ]:
print("Total rows after concat:", len(df_overdose))  # should be same as before (2379)

Total rows after concat: 2379

In [24]:
df_overdose["drug/alcohol_induced_cause"].unique()

<StringArray>
['Drug poisonings (overdose) Unintentional (X40-X44)',
       'Drug poisonings (overdose) Suicide (X60-X64)',
  'Drug poisonings (overdose) Undetermined (Y10-Y14)',
                      'All other drug-induced causes']
Length: 4, dtype: string

In [25]:
OUTPUT2 = "/Users/rosellazheng/Desktop/idsproject/df_overdose_cleaned.csv.csv"
df_overdose.to_csv(OUTPUT2, index=False)

In [26]:
df_overdose

,county,county_code,year,drug/alcohol_induced_cause,drug/alcohol_induced_cause_code,deaths,state
414,Adams County,8001,2009,Drug poisonings (overdose) Unintentional (X40-...,D1,52,CO
415,Adams County,8001,2009,Drug poisonings (overdose) Suicide (X60-X64),D2,15,CO
419,Arapahoe County,8005,2009,Drug poisonings (overdose) Unintentional (X40-...,D1,71,CO
420,Arapahoe County,8005,2009,Drug poisonings (overdose) Suicide (X60-X64),D2,19,CO
426,Boulder County,8013,2009,Drug poisonings (overdose) Unintentional (X40-...,D1,28,CO
...,...,...,...,...,...,...,...
57193,Spokane County,53063,2013,Drug poisonings (overdose) Unintentional (X40-...,D1,48,WA
57194,Spokane County,53063,2013,Drug poisonings (overdose) Suicide (X60-X64),D2,15,WA
57199,Thurston County,53067,2013,Drug poisonings (overdose) Unintentional (X40-...,D1,25,WA
57205,Whatcom County,53073,2013,Drug poisonings (overdose) Unintentional (X40-...,D1,13,WA
57209,Yakima County,53077,2013,Drug poisonings (overdose) Unintentional (X40-...,D1,14,WA

In [27]:
df_overdose.columns.unique

<bound method Index.unique of Index(['county', 'county_code', 'year', 'drug/alcohol_induced_cause',
       'drug/alcohol_induced_cause_code', 'deaths', 'state'],
      dtype='object')>

In [28]:
df_overdose.dtypes

county                             string[python]
county_code                                 int64
year                                        int64
drug/alcohol_induced_cause         string[python]
drug/alcohol_induced_cause_code    string[python]
deaths                                      Int64
state                              string[python]
dtype: object